### PR TITLE
bump rust-bitcoin 0.31

### PR DESCRIPTION
**Pull request by edouardparis**

### CODE REVIEW

**Review by benma — CHANGES_REQUESTED** [review]
thanks!

a lot of needless breaking changes in rust-bitcoin :( 

anyway, the CI fails in examples/btc_sign_psbt.rs, please apply the renames there too.

**Comment by edouardparis** [comment]
Thanks, fixed and rebased

**Comment by darosior** [comment]
> a lot of needless breaking changes in rust-bitcoin :(

Yes, it's unfortunately gotten more common since a couple versions. It's creating needlessly bugprone churn in large codebases.

**Review by benma — APPROVED** [review]
utACK, thx!

**Comment by benma** [comment]
Published as v0.2.3

**Pull request merged**
